#!/usr/bin/env Rscript

install.packages("tidyverse")
install.packages("lubridate")

library(tidyverse)
library(lubridate)

# Win rate vs random over time
alphabeta <- read_csv("./data/alphaBetaSearch.csv")
alphabeta$Time <- ymd_hms(alphabeta$Time)

png(file = "minimax_vs_random.png")
ggplot(data = alphabeta, mapping = aes(x = Time, y = Win)) + 
    ggtitle("TACTIC Win Rate vs Random") +
    xlab("Time") + 
    ylab("Games Won Out of 100") +
    geom_point() +
    geom_smooth(se = FALSE)
dev.off()

# Win rates vs humans over time 
vshumans <- read_csv("./data/minimax_vs_humans.csv")
vshumans$X <- vshumans$("Who played X?")
vshumans$O <- vshumans$("Who played O?")
